version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "dependencies"
      - "lang-rust"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "meta"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    labels:
      - "dependencies"
      - "meta"
    schedule:
      interval: "weekly"

  # C Bindings
  - package-ecosystem: "cargo"
    directory: "/bindings/c"
    labels:
      - "dependencies"
      - "lang-c"
    schedule:
      interval: "weekly"

  # Python Bindings
  - package-ecosystem: "pip"
    directory: "/bindings/python"
    labels:
      - "dependencies"
      - "lang-python"
    schedule:
      interval: "weekly"
