[package]
name = "cpublish"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "cpublish"
crate-type = ["staticlib", "cdylib", "lib"]

# [profile.release]
# panic = "abort"

# [profile.dev]
# panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
publish = { path = "../../" }
bitflags = "2.4.1"
libc = "0.2.152"
async-trait = "0.1.77"
tokio = { version = "1.35.1", features = ["rt"] }

[build-dependencies]
cbindgen = "0.26.0"

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.4.0"
